// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSIONS: KVNamespace;
	ADMIN_USERNAME: "admin";
	ADMIN_PASSWORD: "your_secure_password_here";
	JWT_SECRET: "your_jwt_secret_here_change_this";
	ENVIRONMENT: "development" | "production";
	DB: D1Database;
}
